// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StringMessage struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringMessage) Reset()         { *m = StringMessage{} }
func (m *StringMessage) String() string { return proto.CompactTextString(m) }
func (*StringMessage) ProtoMessage()    {}
func (*StringMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_example_534406c9a7c63282, []int{0}
}
func (m *StringMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringMessage.Unmarshal(m, b)
}
func (m *StringMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringMessage.Marshal(b, m, deterministic)
}
func (dst *StringMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringMessage.Merge(dst, src)
}
func (m *StringMessage) XXX_Size() int {
	return xxx_messageInfo_StringMessage.Size(m)
}
func (m *StringMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_StringMessage.DiscardUnknown(m)
}

var xxx_messageInfo_StringMessage proto.InternalMessageInfo

func (m *StringMessage) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Message struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_example_534406c9a7c63282, []int{1}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (dst *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(dst, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type GetMessageRequest struct {
	MessageId            string                        `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Revision             int64                         `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	Sub                  *GetMessageRequest_SubMessage `protobuf:"bytes,3,opt,name=sub,proto3" json:"sub,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *GetMessageRequest) Reset()         { *m = GetMessageRequest{} }
func (m *GetMessageRequest) String() string { return proto.CompactTextString(m) }
func (*GetMessageRequest) ProtoMessage()    {}
func (*GetMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_example_534406c9a7c63282, []int{2}
}
func (m *GetMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMessageRequest.Unmarshal(m, b)
}
func (m *GetMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMessageRequest.Marshal(b, m, deterministic)
}
func (dst *GetMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMessageRequest.Merge(dst, src)
}
func (m *GetMessageRequest) XXX_Size() int {
	return xxx_messageInfo_GetMessageRequest.Size(m)
}
func (m *GetMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMessageRequest proto.InternalMessageInfo

func (m *GetMessageRequest) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

func (m *GetMessageRequest) GetRevision() int64 {
	if m != nil {
		return m.Revision
	}
	return 0
}

func (m *GetMessageRequest) GetSub() *GetMessageRequest_SubMessage {
	if m != nil {
		return m.Sub
	}
	return nil
}

type GetMessageRequest_SubMessage struct {
	Subfield             string   `protobuf:"bytes,1,opt,name=subfield,proto3" json:"subfield,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMessageRequest_SubMessage) Reset()         { *m = GetMessageRequest_SubMessage{} }
func (m *GetMessageRequest_SubMessage) String() string { return proto.CompactTextString(m) }
func (*GetMessageRequest_SubMessage) ProtoMessage()    {}
func (*GetMessageRequest_SubMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_example_534406c9a7c63282, []int{2, 0}
}
func (m *GetMessageRequest_SubMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMessageRequest_SubMessage.Unmarshal(m, b)
}
func (m *GetMessageRequest_SubMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMessageRequest_SubMessage.Marshal(b, m, deterministic)
}
func (dst *GetMessageRequest_SubMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMessageRequest_SubMessage.Merge(dst, src)
}
func (m *GetMessageRequest_SubMessage) XXX_Size() int {
	return xxx_messageInfo_GetMessageRequest_SubMessage.Size(m)
}
func (m *GetMessageRequest_SubMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMessageRequest_SubMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GetMessageRequest_SubMessage proto.InternalMessageInfo

func (m *GetMessageRequest_SubMessage) GetSubfield() string {
	if m != nil {
		return m.Subfield
	}
	return ""
}

func init() {
	proto.RegisterType((*StringMessage)(nil), "proto.StringMessage")
	proto.RegisterType((*Message)(nil), "proto.Message")
	proto.RegisterType((*GetMessageRequest)(nil), "proto.GetMessageRequest")
	proto.RegisterType((*GetMessageRequest_SubMessage)(nil), "proto.GetMessageRequest.SubMessage")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// YourServiceClient is the client API for YourService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type YourServiceClient interface {
	Echo(ctx context.Context, in *StringMessage, opts ...grpc.CallOption) (*StringMessage, error)
	GetMessage(ctx context.Context, in *GetMessageRequest, opts ...grpc.CallOption) (*Message, error)
}

type yourServiceClient struct {
	cc *grpc.ClientConn
}

func NewYourServiceClient(cc *grpc.ClientConn) YourServiceClient {
	return &yourServiceClient{cc}
}

func (c *yourServiceClient) Echo(ctx context.Context, in *StringMessage, opts ...grpc.CallOption) (*StringMessage, error) {
	out := new(StringMessage)
	err := c.cc.Invoke(ctx, "/proto.YourService/Echo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *yourServiceClient) GetMessage(ctx context.Context, in *GetMessageRequest, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/proto.YourService/GetMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// YourServiceServer is the server API for YourService service.
type YourServiceServer interface {
	Echo(context.Context, *StringMessage) (*StringMessage, error)
	GetMessage(context.Context, *GetMessageRequest) (*Message, error)
}

func RegisterYourServiceServer(s *grpc.Server, srv YourServiceServer) {
	s.RegisterService(&_YourService_serviceDesc, srv)
}

func _YourService_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YourServiceServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.YourService/Echo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(YourServiceServer).Echo(ctx, req.(*StringMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _YourService_GetMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YourServiceServer).GetMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.YourService/GetMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(YourServiceServer).GetMessage(ctx, req.(*GetMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _YourService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.YourService",
	HandlerType: (*YourServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _YourService_Echo_Handler,
		},
		{
			MethodName: "GetMessage",
			Handler:    _YourService_GetMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "example.proto",
}

func init() { proto.RegisterFile("example.proto", fileDescriptor_example_534406c9a7c63282) }

var fileDescriptor_example_534406c9a7c63282 = []byte{
	// 316 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x50, 0xcd, 0x4a, 0xc3, 0x40,
	0x18, 0x64, 0xfb, 0xa3, 0xf6, 0x2b, 0x15, 0x5d, 0x2a, 0xc4, 0xd4, 0x42, 0x8d, 0x08, 0xc1, 0x43,
	0x17, 0x2b, 0x5e, 0xbc, 0x8b, 0x78, 0x10, 0xa1, 0x3d, 0xf5, 0x24, 0x9b, 0xf6, 0x33, 0x5d, 0x48,
	0xb3, 0x35, 0xbb, 0x1b, 0x0a, 0xe2, 0xc5, 0x57, 0xf0, 0x41, 0x3c, 0xfb, 0x1c, 0xbe, 0x82, 0x0f,
	0x22, 0x49, 0x36, 0x0d, 0xa2, 0x9e, 0x76, 0x67, 0xbe, 0xd9, 0x99, 0x6f, 0x07, 0x3a, 0xb8, 0xe6,
	0xcb, 0x55, 0x84, 0xc3, 0x55, 0x22, 0xb5, 0xa4, 0xcd, 0xfc, 0x70, 0x8f, 0x42, 0x29, 0xc3, 0x08,
	0x19, 0x5f, 0x09, 0xc6, 0xe3, 0x58, 0x6a, 0xae, 0x85, 0x8c, 0x55, 0x21, 0xf2, 0x4e, 0xa1, 0x33,
	0xd1, 0x89, 0x88, 0xc3, 0x3b, 0x54, 0x8a, 0x87, 0x48, 0xbb, 0xd0, 0x4c, 0x79, 0x64, 0xd0, 0x21,
	0x03, 0xe2, 0xb7, 0xc6, 0x05, 0xf0, 0xfa, 0xb0, 0x5d, 0x0a, 0x28, 0x34, 0x34, 0xae, 0xb5, 0x9d,
	0xe7, 0x77, 0xef, 0x9d, 0xc0, 0xfe, 0x0d, 0x6a, 0x2b, 0x19, 0xe3, 0x93, 0x41, 0xa5, 0x69, 0x1f,
	0x60, 0x59, 0x30, 0x0f, 0x62, 0x6e, 0xf5, 0x2d, 0xcb, 0xdc, 0xce, 0xa9, 0x0b, 0x3b, 0x09, 0xa6,
	0x42, 0x09, 0x19, 0x3b, 0xb5, 0x01, 0xf1, 0xeb, 0xe3, 0x0d, 0xa6, 0x97, 0x50, 0x57, 0x26, 0x70,
	0xea, 0x03, 0xe2, 0xb7, 0x47, 0x27, 0xc5, 0xae, 0xc3, 0x5f, 0x09, 0xc3, 0x89, 0x09, 0x4a, 0x26,
	0xd3, 0xbb, 0x3e, 0x40, 0x45, 0x65, 0x01, 0xca, 0x04, 0x8f, 0x02, 0xa3, 0x32, 0x7d, 0x83, 0x47,
	0x1f, 0x04, 0xda, 0x53, 0x69, 0x92, 0x09, 0x26, 0xa9, 0x98, 0x21, 0xbd, 0x87, 0xc6, 0xf5, 0x6c,
	0x21, 0x69, 0xd7, 0x66, 0xfd, 0x28, 0xc5, 0xfd, 0x93, 0xf5, 0x7a, 0xaf, 0x9f, 0x5f, 0x6f, 0xb5,
	0x03, 0x6f, 0x8f, 0xa5, 0xe7, 0xcc, 0x76, 0xcf, 0x70, 0xb6, 0x90, 0x57, 0xe4, 0x8c, 0x4e, 0x01,
	0xaa, 0x7d, 0xa9, 0xf3, 0xdf, 0x17, 0xdc, 0x5d, 0x3b, 0x29, 0x4d, 0x8f, 0x73, 0xd3, 0x1e, 0x3d,
	0xcc, 0x4c, 0x6d, 0x59, 0x8a, 0x3d, 0x57, 0x45, 0xbe, 0x04, 0x5b, 0xf9, 0x8b, 0x8b, 0xef, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xc6, 0x6d, 0x5f, 0x8d, 0xf0, 0x01, 0x00, 0x00,
}
